use serde::Serialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
pub enum Severity {
    Critical,
    High,
    Medium,
    Low,
    Info,
}

impl Severity {
    pub fn label(&self) -> &'static str {
        match self {
            Severity::Critical => "CRITICAL",
            Severity::High => "HIGH",
            Severity::Medium => "MEDIUM",
            Severity::Low => "LOW",
            Severity::Info => "INFO",
        }
    }
}

impl std::fmt::Display for Severity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.label())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum AttackCapability {
    NodeBreakout,
    ClusterAdmin,
    CredentialHarvest,
    CodeExecution,
    PersistentBackdoor,
    LateralMovement,
    PrivilegeEscalation,
    TrafficInterception,
    AdmissionBypass,
    InformationDisclosure,
    DenialOfService,
    LogInjection,
    NetworkBypass,
    IdentityForge,
}

impl std::fmt::Display for AttackCapability {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            AttackCapability::NodeBreakout => "Node Breakout",
            AttackCapability::ClusterAdmin => "Cluster Admin Takeover",
            AttackCapability::CredentialHarvest => "Credential Harvest",
            AttackCapability::CodeExecution => "Code Execution",
            AttackCapability::PersistentBackdoor => "Persistent Backdoor",
            AttackCapability::LateralMovement => "Lateral Movement",
            AttackCapability::PrivilegeEscalation => "Privilege Escalation",
            AttackCapability::TrafficInterception => "Traffic Interception",
            AttackCapability::AdmissionBypass => "Admission Bypass",
            AttackCapability::InformationDisclosure => "Information Disclosure",
            AttackCapability::DenialOfService => "Denial of Service",
            AttackCapability::LogInjection => "Log Injection",
            AttackCapability::NetworkBypass => "Network Bypass",
            AttackCapability::IdentityForge => "Identity Forge",
        };
        write!(f, "{}", s)
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct DangerousPermission {
    pub id: &'static str,
    pub resource: &'static str,
    pub verbs: &'static [&'static str],
    pub api_group: &'static str,
    pub severity: Severity,
    pub title: &'static str,
    pub description: &'static str,
    pub attack_path: &'static str,
    pub enables: &'static [AttackCapability],
    pub unconventional: bool,
    pub requires_condition: Option<&'static str>,
}

pub fn all_dangerous_permissions() -> Vec<DangerousPermission> {
    vec![
        // ===== TIER 1: CRITICAL - Direct cluster takeover =====

        DangerousPermission {
            id: "wildcard-all",
            resource: "*",
            verbs: &["*"],
            api_group: "*",
            severity: Severity::Critical,
            title: "Wildcard on All Resources",
            description: "Full access to every resource in the cluster. Equivalent to cluster-admin.",
            attack_path: "Direct cluster-admin equivalent. Do anything.",
            enables: &[AttackCapability::ClusterAdmin],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-clusterrolebindings",
            resource: "clusterrolebindings",
            verbs: &["create", "update", "patch"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Critical,
            title: "Create/Modify ClusterRoleBindings",
            description: "Can bind cluster-admin (or any ClusterRole) to any user or service account.",
            attack_path: "Create a ClusterRoleBinding that binds cluster-admin to your SA -> full cluster access.",
            enables: &[AttackCapability::ClusterAdmin, AttackCapability::PrivilegeEscalation],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-rolebindings",
            resource: "rolebindings",
            verbs: &["create", "update", "patch"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Critical,
            title: "Create/Modify RoleBindings",
            description: "Can bind any Role or ClusterRole to any user or SA within a namespace.",
            attack_path: "Create a RoleBinding referencing a ClusterRole with broad permissions -> escalate within namespace.",
            enables: &[AttackCapability::PrivilegeEscalation],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "escalate-roles",
            resource: "roles",
            verbs: &["escalate"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Critical,
            title: "Escalate Verb on Roles",
            description: "Bypasses the RBAC escalation prevention. Can grant permissions you don't have.",
            attack_path: "Modify an existing Role to add any permission -> bind it to yourself.",
            enables: &[AttackCapability::PrivilegeEscalation, AttackCapability::ClusterAdmin],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "escalate-clusterroles",
            resource: "clusterroles",
            verbs: &["escalate"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Critical,
            title: "Escalate Verb on ClusterRoles",
            description: "Bypasses RBAC escalation prevention at cluster scope.",
            attack_path: "Modify a ClusterRole to add wildcard permissions -> instant cluster-admin.",
            enables: &[AttackCapability::ClusterAdmin, AttackCapability::PrivilegeEscalation],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "bind-roles",
            resource: "roles",
            verbs: &["bind"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Critical,
            title: "Bind Verb on Roles",
            description: "Can bind any Role to any subject, bypassing the normal escalation check on RoleBinding creation.",
            attack_path: "Bind a pre-existing powerful Role to your SA without needing those permissions yourself.",
            enables: &[AttackCapability::PrivilegeEscalation],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "bind-clusterroles",
            resource: "clusterroles",
            verbs: &["bind"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Critical,
            title: "Bind Verb on ClusterRoles",
            description: "Can bind any ClusterRole to any subject at cluster scope.",
            attack_path: "Bind cluster-admin to your SA without needing cluster-admin yourself.",
            enables: &[AttackCapability::ClusterAdmin, AttackCapability::PrivilegeEscalation],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "impersonate-users",
            resource: "users",
            verbs: &["impersonate"],
            api_group: "",
            severity: Severity::Critical,
            title: "Impersonate Users",
            description: "Can make API calls as any user, including cluster admins.",
            attack_path: "kubectl --as=system:admin ... -> act as cluster admin.",
            enables: &[AttackCapability::ClusterAdmin, AttackCapability::IdentityForge],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "impersonate-groups",
            resource: "groups",
            verbs: &["impersonate"],
            api_group: "",
            severity: Severity::Critical,
            title: "Impersonate Groups",
            description: "Can make API calls as any group, including system:masters.",
            attack_path: "kubectl --as-group=system:masters ... -> act as cluster admin group.",
            enables: &[AttackCapability::ClusterAdmin, AttackCapability::IdentityForge],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "impersonate-serviceaccounts",
            resource: "serviceaccounts",
            verbs: &["impersonate"],
            api_group: "",
            severity: Severity::Critical,
            title: "Impersonate Service Accounts",
            description: "Can make API calls as any service account in any namespace.",
            attack_path: "kubectl --as=system:serviceaccount:kube-system:default ... -> act as kube-system SA.",
            enables: &[AttackCapability::PrivilegeEscalation, AttackCapability::IdentityForge, AttackCapability::LateralMovement],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-pods-no-pss",
            resource: "pods",
            verbs: &["create"],
            api_group: "",
            severity: Severity::Critical,
            title: "Create Pods (No PSS Enforcement)",
            description: "Can deploy privileged pods with host mounts when namespace lacks Pod Security Standards.",
            attack_path: "Deploy privileged pod with hostPID + hostNetwork + hostPath:/ -> chroot /mnt -> node root.",
            enables: &[AttackCapability::NodeBreakout, AttackCapability::CodeExecution],
            unconventional: false,
            requires_condition: Some("namespace_no_pss"),
        },
        DangerousPermission {
            id: "create-token-request",
            resource: "serviceaccounts/token",
            verbs: &["create"],
            api_group: "",
            severity: Severity::Critical,
            title: "Create Token Requests",
            description: "Can generate JWT tokens for any service account in the namespace.",
            attack_path: "Mint a token for a privileged SA -> authenticate as that SA -> escalate.",
            enables: &[AttackCapability::IdentityForge, AttackCapability::PrivilegeEscalation],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "approve-csrs",
            resource: "certificatesigningrequests/approval",
            verbs: &["update"],
            api_group: "certificates.k8s.io",
            severity: Severity::Critical,
            title: "Approve Certificate Signing Requests",
            description: "Can approve CSRs to mint valid cluster certificates.",
            attack_path: "Create a CSR for system:masters group -> approve it -> use the cert as cluster-admin.",
            enables: &[AttackCapability::ClusterAdmin, AttackCapability::IdentityForge],
            unconventional: true,
            requires_condition: Some("can_also_create_csr"),
        },
        DangerousPermission {
            id: "create-csrs",
            resource: "certificatesigningrequests",
            verbs: &["create"],
            api_group: "certificates.k8s.io",
            severity: Severity::High,
            title: "Create Certificate Signing Requests",
            description: "Can submit CSRs. Combined with approval rights, can mint cluster certs.",
            attack_path: "Submit a CSR with O=system:masters -> if auto-approved or you can approve -> cluster-admin cert.",
            enables: &[AttackCapability::IdentityForge],
            unconventional: true,
            requires_condition: None,
        },

        // ===== TIER 2: HIGH - Lateral movement / credential access =====

        DangerousPermission {
            id: "create-pods-exec",
            resource: "pods/exec",
            verbs: &["create"],
            api_group: "",
            severity: Severity::High,
            title: "Create Pods/Exec",
            description: "Can exec into running pods and inherit their service account identity.",
            attack_path: "kubectl exec into pod -> read mounted SA token -> pivot to new identity.",
            enables: &[AttackCapability::CodeExecution, AttackCapability::LateralMovement, AttackCapability::CredentialHarvest],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "get-secrets",
            resource: "secrets",
            verbs: &["get", "list"],
            api_group: "",
            severity: Severity::High,
            title: "Read Secrets",
            description: "Can read all secrets in the namespace including SA tokens, TLS certs, and passwords.",
            attack_path: "List secrets -> find SA token secrets -> authenticate as those SAs.",
            enables: &[AttackCapability::CredentialHarvest, AttackCapability::LateralMovement],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-pods-attach",
            resource: "pods/attach",
            verbs: &["create"],
            api_group: "",
            severity: Severity::High,
            title: "Create Pods/Attach",
            description: "Can attach to a running container's stdin/stdout/stderr.",
            attack_path: "Attach to a privileged pod -> interact with its process -> inherit SA.",
            enables: &[AttackCapability::CodeExecution, AttackCapability::LateralMovement],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-pods-ephemeral",
            resource: "pods/ephemeralcontainers",
            verbs: &["create", "update", "patch"],
            api_group: "",
            severity: Severity::High,
            title: "Create Ephemeral Containers",
            description: "Can inject debug containers into running pods without restarting them.",
            attack_path: "Inject an ephemeral container with your payload into a privileged pod -> code execution in its context.",
            enables: &[AttackCapability::CodeExecution, AttackCapability::LateralMovement],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-daemonsets",
            resource: "daemonsets",
            verbs: &["create"],
            api_group: "apps",
            severity: Severity::High,
            title: "Create DaemonSets",
            description: "Can deploy a workload to EVERY node in the cluster simultaneously.",
            attack_path: "Deploy a daemonset with privileged pod spec -> instant root on all nodes.",
            enables: &[AttackCapability::NodeBreakout, AttackCapability::PersistentBackdoor, AttackCapability::CodeExecution],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-deployments",
            resource: "deployments",
            verbs: &["create"],
            api_group: "apps",
            severity: Severity::High,
            title: "Create Deployments",
            description: "Can deploy persistent workloads with automatic restart and scaling.",
            attack_path: "Deploy a deployment with privileged pod template + your C2 payload -> persistent access.",
            enables: &[AttackCapability::CodeExecution, AttackCapability::PersistentBackdoor],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-cronjobs",
            resource: "cronjobs",
            verbs: &["create"],
            api_group: "batch",
            severity: Severity::High,
            title: "Create CronJobs",
            description: "Can schedule recurring workloads. Persistent backdoor via scheduled execution.",
            attack_path: "Create a cronjob running every minute with your payload -> survives pod deletion and cleanup.",
            enables: &[AttackCapability::PersistentBackdoor, AttackCapability::CodeExecution],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-jobs",
            resource: "jobs",
            verbs: &["create"],
            api_group: "batch",
            severity: Severity::High,
            title: "Create Jobs",
            description: "Can run one-shot workloads. Similar to pod creation but with different audit signature.",
            attack_path: "Create a job with privileged pod spec -> one-shot code execution, different audit trail than direct pod create.",
            enables: &[AttackCapability::CodeExecution],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "patch-pods",
            resource: "pods",
            verbs: &["patch", "update"],
            api_group: "",
            severity: Severity::High,
            title: "Patch/Update Pods",
            description: "Can modify running pod specs. May be able to inject containers or change security context.",
            attack_path: "Patch pod to add a privileged container or modify securityContext -> escalate.",
            enables: &[AttackCapability::CodeExecution, AttackCapability::PrivilegeEscalation],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-portforward",
            resource: "pods/portforward",
            verbs: &["create"],
            api_group: "",
            severity: Severity::High,
            title: "Create Port Forwards",
            description: "Can reach internal services not otherwise exposed.",
            attack_path: "Port-forward to internal dashboards, databases, admin UIs -> access internal services.",
            enables: &[AttackCapability::LateralMovement, AttackCapability::InformationDisclosure],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "patch-serviceaccounts",
            resource: "serviceaccounts",
            verbs: &["patch", "update"],
            api_group: "",
            severity: Severity::High,
            title: "Patch Service Accounts",
            description: "Can modify SA configs: add imagePullSecrets, change automount behavior, add secrets.",
            attack_path: "Patch a privileged SA to add your own secret -> mount that secret in a new pod -> credential access.",
            enables: &[AttackCapability::CredentialHarvest, AttackCapability::PrivilegeEscalation],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-services-endpoints",
            resource: "services",
            verbs: &["create", "update", "patch"],
            api_group: "",
            severity: Severity::High,
            title: "Create/Modify Services + Endpoints",
            description: "Can redirect service traffic to attacker-controlled endpoints.",
            attack_path: "Create/modify a Service + Endpoints to point at your pod -> intercept traffic meant for legitimate services.",
            enables: &[AttackCapability::TrafficInterception, AttackCapability::CredentialHarvest],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "modify-endpoints",
            resource: "endpoints",
            verbs: &["create", "update", "patch"],
            api_group: "",
            severity: Severity::High,
            title: "Create/Modify Endpoints",
            description: "Can redirect where service traffic goes without touching the Service object.",
            attack_path: "Modify endpoints for an existing service -> redirect traffic to your pod -> man-in-the-middle.",
            enables: &[AttackCapability::TrafficInterception],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "modify-endpointslices",
            resource: "endpointslices",
            verbs: &["create", "update", "patch"],
            api_group: "discovery.k8s.io",
            severity: Severity::High,
            title: "Create/Modify EndpointSlices",
            description: "EndpointSlices replaced Endpoints in newer clusters. Same traffic redirect capability.",
            attack_path: "Create/modify EndpointSlice -> redirect service traffic to attacker pod.",
            enables: &[AttackCapability::TrafficInterception],
            unconventional: true,
            requires_condition: None,
        },

        // ===== TIER 3: MEDIUM - Bypass / persistence / info disclosure =====

        DangerousPermission {
            id: "create-mutating-webhooks",
            resource: "mutatingwebhookconfigurations",
            verbs: &["create", "update", "patch"],
            api_group: "admissionregistration.k8s.io",
            severity: Severity::Medium,
            title: "Create/Modify Mutating Webhooks",
            description: "Can intercept and modify ALL API requests matching webhook rules. Inject sidecars into every new pod.",
            attack_path: "Deploy a webhook server -> register a MutatingWebhookConfiguration -> inject a sidecar container into every new pod cluster-wide.",
            enables: &[AttackCapability::PersistentBackdoor, AttackCapability::TrafficInterception, AttackCapability::AdmissionBypass],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-validating-webhooks",
            resource: "validatingwebhookconfigurations",
            verbs: &["create", "update", "patch"],
            api_group: "admissionregistration.k8s.io",
            severity: Severity::Medium,
            title: "Create/Modify Validating Webhooks",
            description: "Can intercept and deny API requests. Block legitimate operations or exfiltrate request data.",
            attack_path: "Register a ValidatingWebhookConfiguration pointing to your server -> see all API requests, selectively deny operations.",
            enables: &[AttackCapability::TrafficInterception, AttackCapability::DenialOfService],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "modify-validating-admission-policies",
            resource: "validatingadmissionpolicies",
            verbs: &["create", "update", "patch", "delete"],
            api_group: "admissionregistration.k8s.io",
            severity: Severity::Medium,
            title: "Modify ValidatingAdmissionPolicies",
            description: "Can modify or delete CEL-based admission policies. Disable security guardrails.",
            attack_path: "Delete or weaken ValidatingAdmissionPolicies -> bypass security controls that block privileged pods.",
            enables: &[AttackCapability::AdmissionBypass, AttackCapability::PrivilegeEscalation],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "patch-namespaces",
            resource: "namespaces",
            verbs: &["patch", "update"],
            api_group: "",
            severity: Severity::Medium,
            title: "Patch/Update Namespaces",
            description: "Can modify namespace labels. Remove Pod Security Standard enforcement labels.",
            attack_path: "Patch namespace to remove pod-security.kubernetes.io/enforce label -> namespace now accepts privileged pods.",
            enables: &[AttackCapability::AdmissionBypass, AttackCapability::PrivilegeEscalation],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-pvs",
            resource: "persistentvolumes",
            verbs: &["create"],
            api_group: "",
            severity: Severity::Medium,
            title: "Create PersistentVolumes",
            description: "Can create PVs with hostPath pointing to host filesystem directories.",
            attack_path: "Create a PV with hostPath:/ -> create a PVC that claims it -> mount in your pod -> host filesystem access.",
            enables: &[AttackCapability::NodeBreakout, AttackCapability::CredentialHarvest],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-pvcs",
            resource: "persistentvolumeclaims",
            verbs: &["create"],
            api_group: "",
            severity: Severity::Medium,
            title: "Create PersistentVolumeClaims",
            description: "Can claim existing PVs that may contain data from other workloads.",
            attack_path: "Create a PVC matching an existing PV -> mount it -> read data from other workloads.",
            enables: &[AttackCapability::CredentialHarvest, AttackCapability::InformationDisclosure],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "delete-networkpolicies",
            resource: "networkpolicies",
            verbs: &["delete"],
            api_group: "networking.k8s.io",
            severity: Severity::Medium,
            title: "Delete NetworkPolicies",
            description: "Can remove network segmentation between namespaces and pods.",
            attack_path: "Delete NetworkPolicies -> pods can now communicate freely across namespace boundaries.",
            enables: &[AttackCapability::NetworkBypass, AttackCapability::LateralMovement],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "modify-networkpolicies",
            resource: "networkpolicies",
            verbs: &["create", "update", "patch"],
            api_group: "networking.k8s.io",
            severity: Severity::Medium,
            title: "Create/Modify NetworkPolicies",
            description: "Can modify network segmentation rules to allow your traffic.",
            attack_path: "Create a permissive NetworkPolicy -> allow ingress/egress to/from your attacker pod.",
            enables: &[AttackCapability::NetworkBypass],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "get-pods-log",
            resource: "pods/log",
            verbs: &["get"],
            api_group: "",
            severity: Severity::Medium,
            title: "Read Pod Logs",
            description: "Can read application logs which may contain leaked credentials, tokens, or connection strings.",
            attack_path: "Read logs of all accessible pods -> grep for passwords, tokens, API keys.",
            enables: &[AttackCapability::CredentialHarvest, AttackCapability::InformationDisclosure],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "get-nodes-proxy",
            resource: "nodes/proxy",
            verbs: &["get", "create"],
            api_group: "",
            severity: Severity::Medium,
            title: "Access Node Proxy",
            description: "Can proxy requests through the API server to the Kubelet API on any node.",
            attack_path: "Use node proxy to reach Kubelet API (10250) through the API server -> enumerate pods, exec into containers on that node.",
            enables: &[AttackCapability::LateralMovement, AttackCapability::CodeExecution],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "modify-configmaps-kubesystem",
            resource: "configmaps",
            verbs: &["update", "patch"],
            api_group: "",
            severity: Severity::Medium,
            title: "Modify ConfigMaps (kube-system)",
            description: "Can modify cluster config like kube-proxy, coredns, kubeadm-config in kube-system.",
            attack_path: "Modify coredns configmap -> DNS poisoning within the cluster. Modify kube-proxy -> traffic manipulation.",
            enables: &[AttackCapability::TrafficInterception, AttackCapability::PersistentBackdoor],
            unconventional: true,
            requires_condition: Some("namespace_kube_system"),
        },
        DangerousPermission {
            id: "create-roles",
            resource: "roles",
            verbs: &["create", "update", "patch"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Medium,
            title: "Create/Modify Roles",
            description: "Can create new Roles. Combined with RoleBinding creation, enables self-escalation.",
            attack_path: "Create a Role with broad permissions -> create a RoleBinding to your SA -> escalate.",
            enables: &[AttackCapability::PrivilegeEscalation],
            unconventional: false,
            requires_condition: Some("can_also_create_rolebindings"),
        },
        DangerousPermission {
            id: "create-clusterroles",
            resource: "clusterroles",
            verbs: &["create", "update", "patch"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Medium,
            title: "Create/Modify ClusterRoles",
            description: "Can create new ClusterRoles. Combined with ClusterRoleBinding creation, enables cluster-wide escalation.",
            attack_path: "Create a ClusterRole with * permissions -> bind it to your SA -> cluster-admin.",
            enables: &[AttackCapability::PrivilegeEscalation, AttackCapability::ClusterAdmin],
            unconventional: false,
            requires_condition: Some("can_also_create_clusterrolebindings"),
        },
        DangerousPermission {
            id: "create-statefulsets",
            resource: "statefulsets",
            verbs: &["create"],
            api_group: "apps",
            severity: Severity::Medium,
            title: "Create StatefulSets",
            description: "Can deploy stateful workloads with stable identities and persistent storage.",
            attack_path: "Create a StatefulSet with privileged pod template -> persistent workload with stable network identity.",
            enables: &[AttackCapability::PersistentBackdoor, AttackCapability::CodeExecution],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-replicasets",
            resource: "replicasets",
            verbs: &["create"],
            api_group: "apps",
            severity: Severity::Medium,
            title: "Create ReplicaSets",
            description: "Can deploy workloads bypassing Deployment-level controls.",
            attack_path: "Create a ReplicaSet directly -> deploy pods without deployment audit trail.",
            enables: &[AttackCapability::CodeExecution],
            unconventional: true,
            requires_condition: None,
        },

        // ===== TIER 4: LOW / UNCONVENTIONAL =====

        DangerousPermission {
            id: "get-nodes",
            resource: "nodes",
            verbs: &["get", "list"],
            api_group: "",
            severity: Severity::Low,
            title: "Read Node Information",
            description: "Can enumerate cluster topology: node names, IPs, OS versions, kubelet versions, labels.",
            attack_path: "List nodes -> map cluster topology, identify node IPs for direct Kubelet API probing.",
            enables: &[AttackCapability::InformationDisclosure],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "patch-nodes",
            resource: "nodes",
            verbs: &["patch", "update"],
            api_group: "",
            severity: Severity::Low,
            title: "Patch/Update Nodes",
            description: "Can modify node labels and taints to influence pod scheduling.",
            attack_path: "Taint all nodes except one -> force all new pods to schedule on your compromised node.",
            enables: &[AttackCapability::DenialOfService],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "delete-pods",
            resource: "pods",
            verbs: &["delete"],
            api_group: "",
            severity: Severity::Low,
            title: "Delete Pods",
            description: "Can kill running pods. Force restarts for race conditions or credential capture.",
            attack_path: "Delete a pod -> controller recreates it -> intercept during startup (mount injection, env var capture).",
            enables: &[AttackCapability::DenialOfService],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-events",
            resource: "events",
            verbs: &["create"],
            api_group: "",
            severity: Severity::Low,
            title: "Create Events",
            description: "Can inject fake events into the cluster event stream.",
            attack_path: "Create misleading events -> confuse SOC/monitoring, mask real attack activity.",
            enables: &[AttackCapability::LogInjection],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-leases",
            resource: "leases",
            verbs: &["create", "update", "delete"],
            api_group: "coordination.k8s.io",
            severity: Severity::Low,
            title: "Manipulate Leases",
            description: "Can interfere with leader election for controllers.",
            attack_path: "Delete/modify lease objects -> force leader re-election, potentially cause split-brain in controllers.",
            enables: &[AttackCapability::DenialOfService],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-resourcequotas",
            resource: "resourcequotas",
            verbs: &["create", "update"],
            api_group: "",
            severity: Severity::Low,
            title: "Create/Modify ResourceQuotas",
            description: "Can set resource limits that prevent legitimate workloads from scheduling.",
            attack_path: "Set extremely low quotas -> legitimate pods can't be created -> DoS.",
            enables: &[AttackCapability::DenialOfService],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-limitranges",
            resource: "limitranges",
            verbs: &["create", "update"],
            api_group: "",
            severity: Severity::Low,
            title: "Create/Modify LimitRanges",
            description: "Can set per-pod resource constraints that starve legitimate workloads.",
            attack_path: "Set extremely low limit ranges -> new pods get minimal resources -> performance DoS.",
            enables: &[AttackCapability::DenialOfService],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-priorityclasses",
            resource: "priorityclasses",
            verbs: &["create"],
            api_group: "scheduling.k8s.io",
            severity: Severity::Low,
            title: "Create PriorityClasses",
            description: "Can create high-priority classes that preempt other workloads.",
            attack_path: "Create a PriorityClass with max priority -> deploy your pods with it -> evict legitimate workloads.",
            enables: &[AttackCapability::DenialOfService],
            unconventional: true,
            requires_condition: None,
        },
        DangerousPermission {
            id: "create-pods-with-sa",
            resource: "pods",
            verbs: &["create"],
            api_group: "",
            severity: Severity::High,
            title: "Create Pods (With ServiceAccount Specification)",
            description: "Can create pods running as any service account in the namespace.",
            attack_path: "Create a pod with serviceAccountName set to a privileged SA -> inherit its RBAC permissions.",
            enables: &[AttackCapability::PrivilegeEscalation, AttackCapability::LateralMovement],
            unconventional: false,
            requires_condition: Some("namespace_has_privileged_sa"),
        },
        DangerousPermission {
            id: "get-configmaps",
            resource: "configmaps",
            verbs: &["get", "list"],
            api_group: "",
            severity: Severity::Medium,
            title: "Read ConfigMaps",
            description: "Can read configuration data. ConfigMaps often contain connection strings, config templates, and sometimes credentials.",
            attack_path: "List configmaps -> find kubeconfig templates, connection strings, API keys stored as config.",
            enables: &[AttackCapability::CredentialHarvest, AttackCapability::InformationDisclosure],
            unconventional: false,
            requires_condition: None,
        },
        DangerousPermission {
            id: "delete-clusterrolebindings",
            resource: "clusterrolebindings",
            verbs: &["delete"],
            api_group: "rbac.authorization.k8s.io",
            severity: Severity::Medium,
            title: "Delete ClusterRoleBindings",
            description: "Can remove RBAC bindings from other subjects, disrupting access controls.",
            attack_path: "Delete security-critical bindings -> disable monitoring SAs, break OPA/Gatekeeper, disrupt RBAC enforcement.",
            enables: &[AttackCapability::AdmissionBypass, AttackCapability::DenialOfService],
            unconventional: true,
            requires_condition: None,
        },
    ]
}

pub fn find_matching_permissions(
    resource: &str,
    verb: &str,
    api_group: &str,
) -> Vec<&'static DangerousPermission> {
    // Leak the vec to get 'static lifetime for pattern matching
    let patterns: &'static Vec<DangerousPermission> = Box::leak(Box::new(all_dangerous_permissions()));

    patterns
        .iter()
        .filter(|p| {
            let resource_match = p.resource == "*" || p.resource == resource;
            let verb_match = p.verbs.contains(&"*") || p.verbs.contains(&verb);
            let group_match = p.api_group == "*" || p.api_group == api_group;
            resource_match && verb_match && group_match
        })
        .collect()
}
